// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWF2usz7BfXuqF2atKMakCqogtKO_X3kU',
    appId: '1:801934460564:web:bbdbd511fb9cb224ded681',
    messagingSenderId: '801934460564',
    projectId: 'campus-ah-moment',
    authDomain: 'campus-ah-moment.firebaseapp.com',
    databaseURL: 'https://campus-ah-moment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-ah-moment.firebasestorage.app',
    measurementId: 'G-4Q4NTESEB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftANYIfnLQg2Jbo3CTIhSvkvj1o7NycQ',
    appId: '1:801934460564:android:361b545fb640a28cded681',
    messagingSenderId: '801934460564',
    projectId: 'campus-ah-moment',
    databaseURL: 'https://campus-ah-moment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-ah-moment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLs0_FmJDIjimbLsB28fcqXYcG9Ifrrg',
    appId: '1:801934460564:ios:dbd6b9e9152d509bded681',
    messagingSenderId: '801934460564',
    projectId: 'campus-ah-moment',
    databaseURL: 'https://campus-ah-moment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-ah-moment.firebasestorage.app',
    iosBundleId: 'campus-ah-moment.id.saturdayFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLs0_FmJDIjimbLsB28fcqXYcG9Ifrrg',
    appId: '1:801934460564:ios:dbd6b9e9152d509bded681',
    messagingSenderId: '801934460564',
    projectId: 'campus-ah-moment',
    databaseURL: 'https://campus-ah-moment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-ah-moment.firebasestorage.app',
    iosBundleId: 'campus-ah-moment.id.saturdayFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWF2usz7BfXuqF2atKMakCqogtKO_X3kU',
    appId: '1:801934460564:web:b1f96791d6bc21deded681',
    messagingSenderId: '801934460564',
    projectId: 'campus-ah-moment',
    authDomain: 'campus-ah-moment.firebaseapp.com',
    databaseURL: 'https://campus-ah-moment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-ah-moment.firebasestorage.app',
    measurementId: 'G-VH15G4TTD9',
  );
}
